name: Show last two commit and there differance

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  show-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch the last two commits

      - name: Show last two commits
        id: commits
        run: |
          echo "LAST_TWO=$(git log --pretty=format:"%H" -n 2 | paste -s -d ' ')" >> $GITHUB_OUTPUT

      - name: Show diff between last 2 commits
        run: |
          COMMITS=($(git log --pretty=format:"%H" -n 2))
          echo "Comparing commits: ${COMMITS[1]} -> ${COMMITS[0]}"
          git diff ${COMMITS[1]} ${COMMITS[0]}