name: Triggered by First Workflow

on:
  workflow_run:
    workflows: ["List Changed Files"]
    types:
      - completed

jobs:
  run_job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run after success
        run: echo "Workflow triggered successfully after first workflow completion."